duck push should suggest the first duck

diff --git a/duck b/duck
--- a/duck
+++ b/duck
@@ -87,7 +87,7 @@ case "$1" in
       response=$(curl -m1 --connect-timeout 2 $ip:$quacker_port 2>&1)
       response_code=$?
       case $response_code in
-        56 )
+        56|52)
             findflag=1
             [[ $verbose ]] && prefix="Quack! DuckOS detected on IP: "
             echo $prefix$ip
@@ -103,11 +103,24 @@ case "$1" in
     branch=`git rev-parse --abbrev-ref HEAD 2>/dev/null`
     if [[ $? == 0 ]]; then
       if [[ $branch == "master" ]]; then
+        echo "---> Looking for ducks..."
+        ip=$(duck find-quiet | head -n1)
+        if [[ $ip == "" ]]; then
+          echo "---> No DuckOS hosts found"
+          echo ""
+          echo "Oops! Maybe double check:"
+          echo "  - Your Pi is plugged into a network"
+          echo "  - You've given it some time to boot"
+
+          exit 1
+        fi
+        ip=$(answer "Please enter the device IP (hit enter to use $ip): " $ip)
+
         echo "Pushing master branch..."
-        ip=$(answer "Please enter the device IP: ")
+
         GIT_SSH=`which duck` git push duck@$ip:app master
       else
-        echo "Cannot push branch '$branch', please switch to master."
+        echo "---> Cannot push branch '$branch', please switch to master."
       fi
     else
       echo "---> Oops, no git repository found!"
